meta:
  credhub-params: &credhub-params
    CREDHUB_CA_CERT: ((credhub.ca_cert))
    CREDHUB_SECRET: ((credhub.secret))
    CREDHUB_CLIENT: ((credhub.client))
    CREDHUB_SERVER: ((credhub.server))

  bootstrap-params: &bootstrap-params
    BILLING_ACCOUNT_ID: ((billing_account_id))
    BUCKET_LOCATION: ((bucket_location))
    FOLDER_NAME: ((folder_name))
    GCP_CREDENTIALS_JSON: ((inception_gcp_credentials_json))
    ORGANIZATION_ID: ((organization_id))
    PROJECT_ID: ((gcp_project_id))
    PROJECT_NAME: ((project_name))

groups:
- name: deploy
  jobs:
  - set-pipeline
  - setup-project
- name: teardown
  jobs:
  - set-pipeline
  - teardown-project

resource_types:
- name: terraform
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: srt-gcp-repo
  type: git
  icon: github
  source:
    uri: git@github.com:crsimmons/srt-gcp-pipeline.git
    private_key: ((git_private_key))
    branch: master
    ignore_paths:
    - README.md

- name: concourse-gcp-tf-bootstrap
  type: git
  icon: github
  source:
    uri: git@github.com:EngineerBetter/concourse-gcp-tf-bootstrap.git
    private_key: ((git_private_key))
    branch: master

- name: project-tfstate
  type: gcs
  icon: google-cloud
  source:
    bucket: ((gcp_project_id))
    json_key: ((inception_gcp_credentials_json))
    versioned_file: ci/terraform.tfstate

- name: project-account-and-bucket-terraform
  type: terraform
  icon: terraform
  source:
    env_name: ((env))-project
    backend_type: gcs
    backend_config:
      bucket: ((gcp_project_id))
      prefix: terraform/project-account-and-bucket
    env:
      GOOGLE_CREDENTIALS: ((inception_gcp_credentials_json))
    vars:
      project_id: ((gcp_project_id))
      env: ((env))
      zone_address: ((project_name)).engineerbetter.com

- name: pcf-ops-image
  type: registry-image
  icon: docker
  source:
    repository: engineerbetter/pcf-ops

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: srt-gcp-repo
    trigger: true
  - set_pipeline: self
    file: srt-gcp-repo/ci/pipeline.yml
    var_files:
    - srt-gcp-repo/vars/((env)).yml

- name: setup-project
  plan:
  - in_parallel:
    - get: srt-gcp-repo
      trigger: true
      passed:
      - set-pipeline
    - get: concourse-gcp-tf-bootstrap
    - get: pcf-ops-image
  - task: bootstrap
    file: concourse-gcp-tf-bootstrap/tasks/bootstrap.yml
    params:
      <<: *bootstrap-params
      GCP_FLAKINESS_SLEEP: "60"
    ensure:
      put: project-tfstate
      params:
        file: tfstate-out/terraform.tfstate
  - put: project-account-and-bucket-terraform
    params:
      terraform_source: srt-gcp-repo/terraform/deployments/project-account-and-bucket
  - load_var: service-creds
    file: project-account-and-bucket-terraform/metadata
    format: json
  - task: add-gcp-creds-to-credhub
    image: pcf-ops-image
    file: kf-pipelines/ci/tasks/add-value-to-credhub/task.yml
    input_mapping:
      repo: srt-gcp-repo
    params:
      NAME: /concourse/((concourse_team))/((concourse_pipeline))/gcp_credentials_json
      VALUE: ((.:service_creds.gcp_credentials_json))
      <<: *credhub-params

- name: teardown-project
  plan:
  - in_parallel:
    - get: srt-gcp-repo
      passed:
      - set-pipeline
    - get: concourse-gcp-tf-bootstrap
    - get: project-tfstate
  - task: teardown
    file: concourse-gcp-tf-bootstrap/tasks/teardown.yml
    input_mapping:
      tfstate: project-tfstate
    params:
      <<: *bootstrap-params
